experiment:
  objective: bach_org
  seed: 0
  gpu_num: 1
  device: gpu
dataset:
  name: bach
  fpath: /srv/share4/ychen3237/all_new_pickle/s2s/bach_org_seq2seq_4mm_new.pkl
  batch_size: 32
  subset: full
  shuffle_train: False
  shuffle_val: False
  val_ratio: 0.2
  test_ratio: 0.2
  num_workers: 8
model:
  type: attn_s2s
  attn: True
  hidden_dim: 128
  n_layers: 2
  encoder_dropout: 0.5
  decoder_dropout: 0.5
training:
  lr: 1e-3
  momentum: 0.9
  optimizer_type: AdamW
  dropout: 0.5
  warm_up: 10
  decay_run: 100
  post_run: 500
  save_every_n: 10
validation:
  check_interval: 1.0
  check_ratio: 1.0
logging:
  output_dir: logs/
  progress_bar_refresh_rate: 1