experiment:
  objective: ChordRec
  seed: 0
  gpu_num: 1
  device: gpu
dataset:
  name: mini-imagenet
  directory: D:\Documents\2021Spring\MetaActiveLearn\src\notebooks\data
  meta_batch_size: 16
  subset: full
  shuffle_train: True
  shuffle_val: False
model:
  type: seq2seq
  attn: True
  hidden_dim: 128
  n_layers: 2
  encoder_dropout: 0.5
  decoder_dropout: 0.5
training:
  lr: 1e-3
  momentum: 0.9
  optimizer_type: AdamW
  epochs: 1
  dropout: 0.5
  warm_up: 10
  decay_run: 80
  post_run: 50
validation:
  check_interval: 1.0
  check_ratio: 1.0
logging:
  output_dir: logs/
  progress_bar_refresh_rate: 1